### ISSUE TITLE
app_manifest.json URL

### ISSUE THREAD

**Issue by Workshopshed** [Seeed-Studio/MT3620_Grove_Shield#1]
The [app_manifest.json](
https://github.com/Seeed-Studio/MT3620_Grove_Shield/blob/master/MT3620_Grove_Shield_Library/app_manifest.json) file contains a URL, when I first saw the code, "SeeedIoTHubTest.azure-devices.net" I thought it might be calling home. Probably best to drop this.

**Comment by lanselambor** [comment]
@Workshopshed Nice tweak.
