### ISSUE TITLE
Compatibility Question

### ISSUE THREAD

**Issue by Expecho** [Seeed-Studio/MT3620_Grove_Shield#10]
Can this library be used to develop solutions based on the [AVNET Azure Sphere MT3620 Starter Kit](https://www.avnet.com/shop/us/products/avnet-engineering-services/aes-ms-mt3620-sk-g-3074457345636825680/) which has a built-in grove connector? I'd like to use the Temp and Huminidy SHT31

**Comment by gloveboxes** [comment]
Hey there, not without modification. The I2C support for the SHT31 is proxied through the UART to the Grove Shield. This was done as there was no I2C support when the Azure Sphere was first previewed in 2018. Azure Sphere now has native support for I2C so you'll need to modify the Grove SHT31 driver to talk I2C directly. Check out the C driver at https://www.sensirion.com/en/download-center/humidity-sensors/digital-humidity-sensors-for-various-applications/ or hack the Grove Arduino CPP driver (and convert to C)...

**Comment by Expecho** [comment]
Thank you for your answer. I'm afraid my C skills are not yet good enough to undertake this modifications but thanks anyway!
