### ISSUE TITLE
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage				

### ISSUE THREAD

**Issue by djaus2** [Seeed-Studio/MT3620_Grove_Shield#14]
I get this when opening a Sample

**Comment by matsujirushi** [comment]
Hi @djaus2 ,
Thanks for issue.
I created PR #15 .
Please wait a moment for it to be merged.

**Comment by matsujirushi** [comment]
Fixed.
https://github.com/Seeed-Studio/MT3620_Grove_Shield/commit/19f41c38fd682c990665417c98e5ba870843176b
