### ISSUE TITLE
Azure Sphere SDK 19.11 CMake Build Support

### ISSUE THREAD

**Issue by gloveboxes** [Seeed-Studio/MT3620_Grove_Shield#7]
I've updated the MT3620 Grove Shield to CMake to target Azure Sphere SDK 19.11.  The fork is at https://github.com/gloveboxes/MT3620_Grove_Shield. Could you please review with an eye to accepting a PR. Cheers Dave

**Comment by sadranyi** [comment]
Thanks, been looking for this.

**Comment by Pillar1989** [comment]
Thanks
