### ISSUE TITLE
Azure Sphere real-time capable MT3620_Grove_Shield library

### ISSUE THREAD

**Issue by imbenwolf** [Seeed-Studio/MT3620_Grove_Shield#9]
Hi everybody

While developing with the MT3620 Sphere kit, I noticed the MT3620_Grove_Shield library does not work on real-time apps.

This in very important for us, as we need to connect peripherals to the RT core and send them via intercore-communication to the HL core. This is however impossible for me to implement on my own...

Is there an example of how to use the Light sensor in a Real-Time app or are there plans to create a Real-Time capable MT3620_Grove_Shield library?

Best regards,
Ben

**Comment by Pillar1989** [comment]
Here are some documents that I hope will help you.
https://docs.microsoft.com/en-us/azure-sphere/app-development/rt-app-development-overview
